### PR TITLE
Rework noise modules

### PR DESCRIPTION
**Pull request by gratimax**
I haven't touched this in a while, but seeing as how it's going in to Sponge API I will try to bring it up and finish it.

Flow-noise is based on jlibnoise which is based on libnoise, a C++ library. While all libraries are useful and contain lots of generators, jlibnoise and flow-noise look and feel out of place compared to the rest of the Java ecosystem, especially looking at source modules and that kind of thing.

I tried to make all the modules immutable and take their sources as arguments to their constructors. This way they are easier to chain and construct. There are a few things left though:

- [ ] May be a good idea to add some "operator methods" on the base class Module like add, multiply that create new Add and Multiply instances, making it easier to chain.
- [ ] Some noise, especially Perlin or Curve, are better suited to be constructed by builders instead of passing all the arguments in. Builders can also keep the constants instead of the noise generators themselves.
- [ ] Javadocs
- [ ] There have been a few commits and the history has diverged, especially looking at 68b7c13 on my branch and dc0189b on master. I will rebase, but it looks to be very ugly.

### CODE REVIEW

**Comment by lukespragg** [comment]
It may have been wise to rebase before PRing. ;)

**Comment by gratimax** [comment]
Doing that right now :stuck_out_tongue: Github will keep the PR while it's on the same branch

**Comment by lukespragg** [comment]
PS. Your PR is still trying to PR to master, it needs to PR to develop.

**Comment by gratimax** [comment]
Going to close this, one last time!

**Pull request closed without merging**
