### PR TITLE
Add source archive plugin for maven

### PR DESCRIPTION
**Pull request by antag99**
This pull request adds the [source archive plugin](https://maven.apache.org/plugins/maven-source-plugin/index.html) to `pom.xml`.

### CODE REVIEW

**Comment by lukespragg** [comment]
Is there any benefit to this? We currently only create source jars for deployment.

**Comment by antag99** [comment]
Hmm. I didn't get any source archive using the latest snapshot version.

**Comment by lukespragg** [comment]
We generate them via the deployment script, but only for releases right now.

**Comment by antag99** [comment]
Can you generate them for snapshots versions too? I think it's rather annoying to not be able to look at the source in eclipse.

**Comment by lukespragg** [comment]
All done. ;)

https://oss.sonatype.org/content/groups/public/com/flowpowered/flow-noise/1.0.1-SNAPSHOT/

**Comment by antag99** [comment]
Thanks!

**Pull request closed without merging**
